version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: itstudies12345
      MYSQL_DATABASE: csd214-lab0
      MYSQL_USER: csd214
      MYSQL_PASSWORD: itstudies12345
    ports:
      - "3333:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    restart: always

volumes:
  db_data:
